### ISSUE TITLE
Default anchor styles

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#246]
Kinda like we have default body type styles (on `p` elements), should we implement default anchor styles on `a` elements without needing to use class names?

**Comment by jstnjns** [comment]
We have default body type styles, but those shouldn't isolate to just `p`.  Because `a` are used for more than just links, we should be careful about our approach.  I think we should probably just add a class, something like `.mc-text-link` for semantic use, but even that gets tricky because our links are styled many different ways across the application.

**Comment by jstnjns** [comment]
(did not mean to close)

**Comment by jstnjns** [comment]
(sure did)
