### ISSUE TITLE
Should checkboxes be interactive without react?

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#255]
We rely on the `.mc-input-checkbox--checked` class to render the checked style. Should we instead target `:checked` so you don't need react? Currently writing custom jquery to get this behavior on the SEO landing page.

**Comment by a-axton** [comment]
If we can get it to work that way then definitely. We might have to re-arrange the elements and use a `+` selector to style the faux checkbox

**Comment by jstnjns** [comment]
The checkbox is a controlled component.  The styling is based at the wrapping `label` level.  The only reason I could see changing this as a problem is because we're actually styling a faux checkbox instead of an actual input, and that if we are going to require that users generate this level of markup, we might as well require them to implement it with React.

I do, however, understand the desire to get a non-React implementation.  If you can make it work both ways, I'm for it.

**Comment by jstnjns** [comment]
talked offline, not as simple as previously thought
