### ISSUE TITLE
Text Area question

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#267]
I have a text area that doesn't use any label but I want to show an error label when the text area is empty. Is it possible?

**Comment by jstnjns** [comment]
Errors show up whether there's a label or not: https://github.com/yankaindustries/mc-components/blob/develop/src/components/Textarea/index.js#L91

**Comment by bernabe9** [comment]
Yes, but we only show the label if there is a value on the input. So, my question was if the text area is EMPTY and I want to show the error(without label). For example: A required error.

Take a look to the class name: `--no-label`: https://github.com/yankaindustries/mc-components/blob/develop/src/components/Textarea/index.js#L82 it doesn't work if there isn't a label.


Screenshot:

![screen shot 2018-10-30 at 9 28 58 am](https://user-images.githubusercontent.com/18464392/47718092-420fcd80-dc26-11e8-93a5-fcc3ad6e2d48.png)

**Comment by stephenp** [comment]
I think what @jstnjns was implying was the style of mc-components input boxes DO have labels inside the inputs. That's the designed style at the moment that was initially agreed upon by design.

We're currently focusing on getting everything aligned and there will be growing pains until we're in alignment - things looking slightly different than comps is expected and acceptable per Alex / Sean until comps are finalized

(So we don't want to write custom style overrides on a per-project basis just to get it to match the comp before mc-components has time to catch up on design changes).

If you run into issues with designers saying "it doesn't match the comp", please refer them to Alex Tam, Sean Kesterson, myself, and or Jesse.

**Comment by bernabe9** [comment]
@stephenp @jstnjns  I understand. But that doesn't answer my question.

Can I show the error message without the label prop? I can do it with the Input component but not with the TextArea. Check out the screenshot.

**Comment by jstnjns** [comment]
I see.  It looks like this state was overlooked.  It should be there, as you said it is in `Input`.  Pushing a fix now.  Might be easier to ping me on Slack about these sorts of things.
