### ISSUE TITLE
How to handle cursor use cases on tile components

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#495]
It seems like we're coming across instances where the `Tile` component should _not_ have the `cursor: pointer;` css style set.

https://ourmasterclass.slack.com/archives/CGH3BN06M/p1558644695014000

Should we:
- Make the default a pointer, but have an option for users to unset that?
- Leave it as it is, but have users write custom css to unset?
- Change to no cursor by default and have users add cursor pointers?

Open to discussion!

@jstnjns @tamarajordan

**Comment by tamarajordan** [comment]
I like keeping the cursor set to pointer as a default, since I think generally tiles are and should be clickable. So I'd vote in favor of custom CSS or allowing people to unset the default cursor styling

**Comment by jstnjns** [comment]
I wonder if it's best to attach the pointer "style" (i put it in quotes because i'm not sure i would even classify it as that, more like an interaction indicator) to attributes that actually need indication, like `[href]` or `[onClick]`. i feel like this approach would solve our needs without having to override styles based on a change in the default interaction

**Comment by bcfancher-masterclass** [comment]
I def vote for only using pointer style when href or onClick props are set.  @jstnjns lemme know and I'll make it so

**Comment by bcfancher-mc** [comment]
gah, just noticed we're not currently passing any onClick or href stuffs to tiles, only on the tile parent  >.<

**Comment by bcfancher-mc** [comment]
necessary changes have been made in MC and MCC repos
